spring:
  config:
    activate:
      on-profile: local

  batch:
    jdbc:
      initialize-schema: NEVER
      
  datasource:
    url: jdbc:mysql://localhost:3306/BATC?useUnicode=true&characterEncoding=utf8
    username: root
    password: new1234!
    driver-class-name: com.mysql.jdbc.Driver
    
    quartzDataSource: 
      url: jdbc:mysql://localhost:3306/BATC?useUnicode=true&characterEncoding=utf8
      username: root
      password: new1234!
      driver-class-name: com.mysql.jdbc.Driver
      
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: quartzDataSource
            useProperties: true
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 1000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          
 
